// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, firstname, lastname, birth, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Birth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, firstname, lastname, birth, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Birth     time.Time `json:"birth"`
	CreatedAt int64     `json:"created_at"`
	UpdatedAt int64     `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Birth,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
