db:
  name: "user"
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  pass: "secret"
  pool: 
    minSize: 1
    maxSize: 3
    
token:
  dur: "20m"
  secret: "4ca9f25cf0ac1d7bc64b6731261ec6f3be3170225f847858f4de3c9ad5ed50e0"
 
server:
  service_name: "svc-user"