// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"github.com/google/uuid"
)

type Permission struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       int16 `json:"role_id"`
	PermissionID int16 `json:"permission_id"`
}

type UserBannedPermission struct {
	ID           int64     `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	PermissionID int16     `json:"permission_id"`
	BannedAt     int64     `json:"banned_at"`
	BannedExp    int64     `json:"banned_exp"`
}

type UserBannedRole struct {
	ID        int64     `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	RoleID    int16     `json:"role_id"`
	BannedAt  int64     `json:"banned_at"`
	BannedExp int64     `json:"banned_exp"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID int16     `json:"role_id"`
}
