// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"context"
)

type Querier interface {
	BannUserPermission(ctx context.Context, arg BannUserPermissionParams) error
	Permission(ctx context.Context, name string) (Permission, error)
	Role(ctx context.Context, name string) (Role, error)
	RoleGrantPermission(ctx context.Context, arg RoleGrantPermissionParams) error
	UserBannedPermission(ctx context.Context, arg UserBannedPermissionParams) (UserBannedPermission, error)
	UserPermit(ctx context.Context, arg UserPermitParams) (RolePermission, error)
}

var _ Querier = (*Queries)(nil)
