// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	RolePermissions(ctx context.Context, roleID int16) ([]RolePermissionsRow, error)
	UserBannedPermissions(ctx context.Context, arg UserBannedPermissionsParams) ([]UserBannedPermission, error)
	UserBannedRoles(ctx context.Context, arg UserBannedRolesParams) ([]UserBannedRole, error)
	UserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
}

var _ Querier = (*Queries)(nil)
