// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: auth.sql

package postgres

import (
	"context"
)

const getAuth = `-- name: GetAuth :one
SELECT id, username, password FROM auth WHERE username = $1
`

func (q *Queries) GetAuth(ctx context.Context, username string) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuth, username)
	var i Auth
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
