// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Auth struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Password string    `json:"password"`
}

type AuthUser struct {
	AuthID uuid.UUID `json:"auth_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Friend struct {
	User1      uuid.UUID    `json:"user1"`
	User2      uuid.UUID    `json:"user2"`
	ApprovedAt sql.NullTime `json:"approved_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Birth     time.Time `json:"birth"`
	CreatedAt time.Time `json:"created_at"`
}
