// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"context"
)

type Querier interface {
	GetAuth(ctx context.Context, username string) (Auth, error)
}

var _ Querier = (*Queries)(nil)
