// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *LoginResponse) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Birth                string   `protobuf:"bytes,5,opt,name=birth,proto3" json:"birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterRequest) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

type RegisterResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.RegisterResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x42, 0x03, 0xed, 0xaa, 0x15, 0xc5, 0xf4, 0x60, 0x45, 0x1c, 0x90, 0x4f, 0x1c, 0x50,
	0x0e, 0x20, 0xbe, 0x00, 0x89, 0x13, 0x07, 0x14, 0xc1, 0x07, 0x24, 0x74, 0x09, 0x56, 0x68, 0x6c,
	0xbc, 0x2e, 0x7c, 0x0b, 0x7f, 0x8b, 0xfc, 0x08, 0x49, 0xb8, 0x21, 0x6e, 0x99, 0x19, 0xcd, 0xec,
	0xec, 0xc6, 0xb0, 0x22, 0x34, 0x1f, 0xf2, 0x19, 0x0b, 0x6d, 0x94, 0x55, 0x2c, 0xd5, 0xb5, 0xb8,
	0x83, 0xe5, 0xbd, 0x6a, 0x64, 0x57, 0xe2, 0xfb, 0x1e, 0xc9, 0xb2, 0x1c, 0xe6, 0x7b, 0x42, 0xd3,
	0x55, 0x3b, 0xe4, 0xc9, 0x79, 0x72, 0xb1, 0x28, 0x7f, 0xb0, 0xd3, 0x74, 0x45, 0xf4, 0xa9, 0xcc,
	0x96, 0xa7, 0x41, 0xeb, 0xb1, 0x68, 0x61, 0x15, 0x73, 0x48, 0xab, 0x8e, 0x90, 0x09, 0x58, 0x9a,
	0xf8, 0x7d, 0xab, 0xb6, 0x21, 0x2c, 0x2b, 0x27, 0x1c, 0x3b, 0x83, 0x85, 0x0b, 0x7f, 0x54, 0x2d,
	0x76, 0x31, 0x71, 0x20, 0x18, 0x87, 0xa3, 0x1d, 0x12, 0x55, 0x0d, 0xf2, 0x03, 0xaf, 0xf5, 0x50,
	0x7c, 0x25, 0x70, 0x5c, 0x62, 0x23, 0xc9, 0xa2, 0xf9, 0x67, 0x71, 0xd7, 0xe1, 0x45, 0x1a, 0xb2,
	0xde, 0x18, 0xe6, 0x0c, 0x84, 0x73, 0xbe, 0x55, 0x51, 0x9c, 0x05, 0x67, 0x8f, 0xd9, 0x06, 0xb2,
	0x5a, 0x1a, 0xfb, 0xca, 0x33, 0x2f, 0x04, 0x20, 0x1e, 0x60, 0x3d, 0x54, 0xfb, 0xc3, 0x2d, 0x46,
	0xdb, 0xa6, 0x93, 0x6d, 0xaf, 0x5a, 0x98, 0x3d, 0x11, 0x1a, 0x76, 0x09, 0x99, 0x3f, 0x31, 0x5b,
	0x17, 0xba, 0x2e, 0xc6, 0x7f, 0x2d, 0x3f, 0x19, 0x31, 0x71, 0xe6, 0x0d, 0xcc, 0xfb, 0x1e, 0xec,
	0xd4, 0xc9, 0xbf, 0x0e, 0x96, 0x6f, 0xa6, 0x64, 0xb0, 0xd5, 0x87, 0xfe, 0x69, 0x5c, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x48, 0xce, 0x23, 0xf1, 0x2b, 0x02, 0x00, 0x00,
}
