// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authorization.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckPermissionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionName       string   `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionRequest) Reset()         { *m = CheckPermissionRequest{} }
func (m *CheckPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionRequest) ProtoMessage()    {}
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{0}
}

func (m *CheckPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionRequest.Unmarshal(m, b)
}
func (m *CheckPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionRequest.Marshal(b, m, deterministic)
}
func (m *CheckPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionRequest.Merge(m, src)
}
func (m *CheckPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionRequest.Size(m)
}
func (m *CheckPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionRequest proto.InternalMessageInfo

func (m *CheckPermissionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CheckPermissionRequest) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

type CheckPermissionResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionResponse) Reset()         { *m = CheckPermissionResponse{} }
func (m *CheckPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionResponse) ProtoMessage()    {}
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{1}
}

func (m *CheckPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionResponse.Unmarshal(m, b)
}
func (m *CheckPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionResponse.Marshal(b, m, deterministic)
}
func (m *CheckPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionResponse.Merge(m, src)
}
func (m *CheckPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionResponse.Size(m)
}
func (m *CheckPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionResponse proto.InternalMessageInfo

func (m *CheckPermissionResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CheckPermissionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BannStatusRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionName       string   `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannStatusRequest) Reset()         { *m = BannStatusRequest{} }
func (m *BannStatusRequest) String() string { return proto.CompactTextString(m) }
func (*BannStatusRequest) ProtoMessage()    {}
func (*BannStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{2}
}

func (m *BannStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannStatusRequest.Unmarshal(m, b)
}
func (m *BannStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannStatusRequest.Marshal(b, m, deterministic)
}
func (m *BannStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannStatusRequest.Merge(m, src)
}
func (m *BannStatusRequest) XXX_Size() int {
	return xxx_messageInfo_BannStatusRequest.Size(m)
}
func (m *BannStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BannStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BannStatusRequest proto.InternalMessageInfo

func (m *BannStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BannStatusRequest) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

type BannStatusResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PermissionName       string   `protobuf:"bytes,3,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	BannAt               int64    `protobuf:"varint,4,opt,name=bannAt,proto3" json:"bannAt,omitempty"`
	BannedExp            int64    `protobuf:"varint,5,opt,name=bannedExp,proto3" json:"bannedExp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannStatusResponse) Reset()         { *m = BannStatusResponse{} }
func (m *BannStatusResponse) String() string { return proto.CompactTextString(m) }
func (*BannStatusResponse) ProtoMessage()    {}
func (*BannStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{3}
}

func (m *BannStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannStatusResponse.Unmarshal(m, b)
}
func (m *BannStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannStatusResponse.Marshal(b, m, deterministic)
}
func (m *BannStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannStatusResponse.Merge(m, src)
}
func (m *BannStatusResponse) XXX_Size() int {
	return xxx_messageInfo_BannStatusResponse.Size(m)
}
func (m *BannStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BannStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BannStatusResponse proto.InternalMessageInfo

func (m *BannStatusResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *BannStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BannStatusResponse) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

func (m *BannStatusResponse) GetBannAt() int64 {
	if m != nil {
		return m.BannAt
	}
	return 0
}

func (m *BannStatusResponse) GetBannedExp() int64 {
	if m != nil {
		return m.BannedExp
	}
	return 0
}

type GiveRoleRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiveRoleRequest) Reset()         { *m = GiveRoleRequest{} }
func (m *GiveRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GiveRoleRequest) ProtoMessage()    {}
func (*GiveRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{4}
}

func (m *GiveRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiveRoleRequest.Unmarshal(m, b)
}
func (m *GiveRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiveRoleRequest.Marshal(b, m, deterministic)
}
func (m *GiveRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiveRoleRequest.Merge(m, src)
}
func (m *GiveRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GiveRoleRequest.Size(m)
}
func (m *GiveRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GiveRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GiveRoleRequest proto.InternalMessageInfo

func (m *GiveRoleRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GiveRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type GiveRoleResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiveRoleResponse) Reset()         { *m = GiveRoleResponse{} }
func (m *GiveRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GiveRoleResponse) ProtoMessage()    {}
func (*GiveRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{5}
}

func (m *GiveRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiveRoleResponse.Unmarshal(m, b)
}
func (m *GiveRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiveRoleResponse.Marshal(b, m, deterministic)
}
func (m *GiveRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiveRoleResponse.Merge(m, src)
}
func (m *GiveRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GiveRoleResponse.Size(m)
}
func (m *GiveRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GiveRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GiveRoleResponse proto.InternalMessageInfo

func (m *GiveRoleResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GiveRoleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckPermissionRequest)(nil), "pb.CheckPermissionRequest")
	proto.RegisterType((*CheckPermissionResponse)(nil), "pb.CheckPermissionResponse")
	proto.RegisterType((*BannStatusRequest)(nil), "pb.BannStatusRequest")
	proto.RegisterType((*BannStatusResponse)(nil), "pb.BannStatusResponse")
	proto.RegisterType((*GiveRoleRequest)(nil), "pb.GiveRoleRequest")
	proto.RegisterType((*GiveRoleResponse)(nil), "pb.GiveRoleResponse")
}

func init() {
	proto.RegisterFile("authorization.proto", fileDescriptor_1dbbe58d1e51a797)
}

var fileDescriptor_1dbbe58d1e51a797 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xbb, 0x4e, 0xeb, 0x40,
	0x10, 0x95, 0x9d, 0x9b, 0xd7, 0xe8, 0xde, 0xe4, 0x32, 0x81, 0xc4, 0x72, 0x28, 0x22, 0x37, 0xa4,
	0x4a, 0x01, 0xa2, 0xa2, 0x0a, 0x11, 0x8a, 0x40, 0x08, 0x05, 0x53, 0x50, 0x46, 0x6b, 0x3c, 0x22,
	0x2b, 0xe2, 0x5d, 0xe3, 0x5d, 0x23, 0xc4, 0x5f, 0xf1, 0x25, 0xfc, 0x12, 0xb2, 0xb1, 0xe3, 0x3c,
	0xdc, 0x91, 0x6e, 0xe7, 0xcc, 0xcc, 0x99, 0x39, 0xe3, 0x63, 0xe8, 0xb0, 0x58, 0x2f, 0x64, 0xc4,
	0x3f, 0x98, 0xe6, 0x52, 0x8c, 0xc2, 0x48, 0x6a, 0x89, 0x66, 0xe8, 0x39, 0xf7, 0xd0, 0x9d, 0x2c,
	0xe8, 0xe9, 0x65, 0x46, 0x51, 0xc0, 0x95, 0xe2, 0x52, 0xb8, 0xf4, 0x1a, 0x93, 0xd2, 0xd8, 0x02,
	0x93, 0xfb, 0x96, 0x31, 0x30, 0x86, 0x4d, 0xd7, 0xe4, 0x3e, 0x9e, 0x40, 0x3b, 0x5c, 0x15, 0xcd,
	0x05, 0x0b, 0xc8, 0x32, 0xd3, 0x64, 0xab, 0x80, 0xef, 0x58, 0x40, 0xce, 0x23, 0xf4, 0x76, 0x28,
	0x55, 0x28, 0x85, 0x22, 0x74, 0xe0, 0x6f, 0x94, 0xbd, 0x27, 0xd2, 0xa7, 0x94, 0xbd, 0xea, 0x6e,
	0x60, 0x68, 0x41, 0x3d, 0x20, 0xa5, 0xd8, 0x73, 0xce, 0x9f, 0x87, 0xce, 0x2d, 0x1c, 0x5c, 0x32,
	0x21, 0x1e, 0x34, 0xd3, 0xb1, 0xfa, 0xf5, 0x9a, 0x9f, 0x06, 0xe0, 0x3a, 0xdd, 0x3e, 0x56, 0x2c,
	0x9b, 0x5e, 0x29, 0x9b, 0x8e, 0x5d, 0xa8, 0x79, 0x4c, 0x88, 0xb1, 0xb6, 0xfe, 0x0c, 0x8c, 0x61,
	0xc5, 0xcd, 0x22, 0x3c, 0x86, 0x66, 0xf2, 0x22, 0xff, 0xea, 0x3d, 0xb4, 0xaa, 0x69, 0xaa, 0x00,
	0x9c, 0x29, 0xb4, 0xa7, 0xfc, 0x8d, 0x5c, 0xb9, 0xa4, 0x5c, 0x7f, 0x0f, 0xea, 0xb1, 0xa2, 0x68,
	0xbe, 0x3a, 0x42, 0x2d, 0x09, 0xaf, 0x7d, 0xec, 0x43, 0x33, 0x92, 0x4b, 0x5a, 0x3f, 0x41, 0x23,
	0x01, 0x52, 0xf1, 0x33, 0xf8, 0x5f, 0x10, 0xed, 0x43, 0xf9, 0xe9, 0x97, 0x01, 0xff, 0xc6, 0xeb,
	0x26, 0xc3, 0x1b, 0x68, 0x6f, 0xf9, 0x00, 0xed, 0x51, 0xe8, 0x8d, 0xca, 0xfd, 0x66, 0xf7, 0x4b,
	0x73, 0xd9, 0x6e, 0x17, 0x00, 0xc5, 0xb7, 0xc2, 0xa3, 0xa4, 0x74, 0xc7, 0x0a, 0x76, 0x77, 0x1b,
	0xce, 0x9a, 0xcf, 0xa1, 0x91, 0x8b, 0xc5, 0x4e, 0x52, 0xb3, 0x75, 0x43, 0xfb, 0x70, 0x13, 0xfc,
	0x69, 0xf3, 0x6a, 0xe9, 0x5f, 0x72, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x89, 0x95, 0x48, 0xf2,
	0x3c, 0x03, 0x00, 0x00,
}
